[project]
name = "it"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "datasets>=3.6.0",
    "matplotlib>=3.10.7",
    "seaborn>=0.13.2",
]
